### ISSUE TITLE
Authentication to work on multiple pages

### ISSUE THREAD

**Issue by Jayant0jha** [Jayant0jha/SampleAngularApp#1]
Currently, the authentication flow works only for the home component, and if any other component is added, auth token cannot be recieved for that. So There is a requirement to complete flow for auth on multiple pages. Pls don't use localstorage to save user info, if authstate can be used it will be best.
You may create a new component other than home component and try establishing auth flow for the same.

**Comment by manojreddy-dev** [comment]
Can I work on the issue

**Comment by Jayant0jha** [comment]
@manu143manoj sure, go ahead.

**Comment by Jayant0jha** [comment]
Issue is again open for all.

**Comment by jilimm** [comment]
Hi can i try working on this?

**Comment by Jayant0jha** [comment]
Sure, go on!

**Comment by jilimm** [comment]
made a PR. do check if its in line with the requirements
